### ISSUE TITLE
Error when trying to include service

### ISSUE THREAD

**Issue by zmp-virgru** [ros/rosbag_snapshot#11]
I'm trying to call the TriggerSnapshot service from within my ros node, but when I include the service in my node like this:

`#include <rosbag_snapshot_msgs/TriggerSnapshot.h>`

without adding any further code, I get the following error. I have added rosbag_snapshot_msgs to my CMakeLists and package.xml. Any idea what could be causing this?

`/opt/ros/noetic/include/rosbag_snapshot_msgs/TriggerSnapshotResponse.h:52:125: error: expected unqualified-id before numeric constant
   52 |   static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  NO_DATA;
      |                                                                                                                             ^~~~~~~
/opt/ros/noetic/include/rosbag_snapshot_msgs/TriggerSnapshotResponse.h:68:53: error: expected unqualified-id before numeric constant
   68 |       TriggerSnapshotResponse_<ContainerAllocator>::NO_DATA =
      |                                                     ^~~~~~~
`

**Comment by DLu** [comment]
What OS is this?

**Comment by zmp-virgru** [comment]
Ubuntu 20.04.1 LTS

**Comment by zmp-virgru** [comment]
It seems it is a conflict of NO_DATA which is defined as "4" in netdb.h which is used by boost. Can work around it by including in this way:

`#undef NO_DATA
#include <rosbag_snapshot_msgs/TriggerSnapshot.h>
#define NO_DATA 4`

Could also rename the define, if that is ok with you I can make a PR.

**Comment by DLu** [comment]
Ah, I see. Now it makes more sense. 

Yeah, a PR to rename the field of the service to be NO_DATA_MESSAGE would be fantastic.
