### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jorgenfb** [ros/rosbag_snapshot#17]
I think it would be useful to have a message count limit (in addition to the memory and time limits). 

This could probably work very similar to the memory limit. Negative values mean no limit. Any positive integer will limit the number of messages in the buffer.

Use case:
There are some topics where only the last message is interesting. Examples are state topics where only the current state is relevant. In my case I also have a point cloud topic that I want to include, but only the last point cloud is relevant (to save bandwith and disk space).

If there is interest in adding this, I can help with the implementation. Just want to hear your thoughts first.

**Comment by DLu** [comment]
That seems like a reasonable option

**Comment by jorgenfb** [comment]
I have submitted a PR (#18) adding the option to limit the number of message per topic

**Comment by DLu** [comment]
Thank you for the contribution!
