### ISSUE TITLE
Question: does "buffered data" get saved in RAM?

### ISSUE THREAD

**Issue by JanezCim** [ros/rosbag_snapshot#22]
Quoting from README:

"It subscribes to topics and maintains a buffer of recent messages like a dash cam..."

I'm interested in where this data in buffer is saved - i would assume somewhere in RAM right? Because if its on harddisk space it might aid to corrupting SD cards that have a shockingly low read/write ability (eg. on a RaspberryPI).

Otherwise the tool looks amazing, thank you for the contribution!

**Comment by DLu** [comment]
The queue is stored in RAM until the trigger requests that it be written to disk. 

Enjoy!
