### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by emiralpayar** [ros/rosbag_snapshot#33]
Hello, I am launching rosbag_snapshot in my environment at the start up and it does not get enabled initially. Since it is not enabled there should be no buffering to the memory but I observed a great CPU usage while it is not used at all. I think it starts buffering when launched by a launch file. Is there a way to launch the node without starting buffering and starting the buffering by calling enable_snapshot service?

Thanks in advance

**Comment by DLu** [comment]
Glad we could help?
